### ISSUE TITLE
Actions

### ISSUE THREAD

**Issue by jayvdb** [tolomea/django-data-browser#12]
It would be useful to be able to use DDB to filter records of any model, and then perform a action on them.

The obvious source of "actions" is Django admin list actions.  That re-uses an existing well defined interface for actions.  This would allow removal of the DDB "csv" and "json" export , as those could be provided by https://github.com/saxix/django-adminactions or many other apps providing that type of functional.

Another very interesting app I am now starting to use is https://django-action-framework.readthedocs.io/ which allows defining actions generically against models in a way that can be accessed by other apps.  Those actions can be fairly easily added to Django admin , so they would automatically become available to DDB if it uses Django admin actions.

However DDB actions can also be exposed via DRF which might be a way that DDB can access the actions from the JS layer.  I haven't tried this yet, and would prefer to use django admin for many types of actions which I dont feel comfortable exposing over DRF unless I also built lots of security related tests to ensure it could not accidentally be exposed to non-admins.

**Comment by tolomea** [comment]
I agree that if DDB is going to support any sense of write actions then it should start with the existing admin ones.

I think the JSON and CSV exports are core parts of DDB data access functionality and additionally they tie to the public views as well (I have very mixed feelings about public views being disabled by default).

I have no problem with exposing admin actions if someone were to put a pull together for it. Happy to discuss how that might work. In general I'd like to avoid picking up DRF as a dependency. I would want to expose it in a DDB specific API that ties direct into the admin functionality much like how the rest of DDB works.

**Comment by tolomea** [comment]
nts: I think any "admin" column could have the bulk actions from the associated admin in the title right click menu

**Comment by tolomea** [comment]
This is committed and can be installed direct from github, I will release it sometime in the next week or two, might do a 3.2 with everything I get done over the holidays (in between Cyberpunk sessions).
If you could give it a try sometime and let me know how it goes that'd be appreciated.
