### ISSUE TITLE
Split build.sh

### ISSUE THREAD

**Issue by jayvdb** [tolomea/django-data-browser#18]
Do you mind splitting build.sh , so the frontend build can be run by someone like me, without invoking publish-like functionality which isnt appropriate for me.

**Comment by tolomea** [comment]
I don't object per se, however I'm not clear on the need.
It doesn't actually do publish stuff, it just echo's the commands out, it does do the packaging stuff, but that is harmless.
Which bit is problematic for you?

If this is about runtime when hacking on the frontend code then I would strongly encourage you to get the DATA_BROWSER_DEV=True flow working as it's way more pleasant to work with frontend auto reloading.

**Comment by tolomea** [comment]
@jayvdb I'm still curious about your usecase and how the current file is problematic for that.

**Comment by jayvdb** [comment]
It is the packaging stuff I don't want to run unnecessarily.  It consumes my time.

**Comment by tolomea** [comment]
It still sounds like maybe you should be using the JS dev server.
But it's no particular issue to me to split it.

**Comment by jayvdb** [comment]
This is for packaging of non-released versions (so I can test them), not for development.
Anyways, much appreciated. `build_fe.sh` is perfect; I can use that in my scripts and assume it will work most of the time. ;-)

**Comment by tolomea** [comment]
you got to this a little faster than I expected, so you should probably be aware that I force updated master in between
