### ISSUE TITLE
Creating/displaying new model

### ISSUE THREAD

**Issue by Dleau** [tolomea/django-data-browser#28]
Hi, I'm (very) new to Django and to django-data-browser (which seems like an awesome project). I'm looking to create a new model from the baseline and add it to `/data-browser`. Right now, I see models `auth.Group`, `auth.User`, and `data_browser.View`. How could I go about doing this? Apologies if this is an easy question! Thank you for the help!

**Comment by tolomea** [comment]
The Data Browser is driven by the Django Admin, anything you see in the Admin is visible in the Browser. So to add a model to the Data Browser it just needs to be added to the Admin.

The official Django tutorial talks about the Admin here https://docs.djangoproject.com/en/3.1/intro/tutorial02/#introducing-the-django-admin

In general if you are new to Django I would strong encourage you to work through the whole of the official tutorial from the start. It's not particularly long and it introduces all of the main features of Django.

**Comment by Dleau** [comment]
Thank you, this is very helpful. Enjoy the weekend!

**Comment by tolomea** [comment]
:)

I'm going to close this now, feel free to open another issue if you have other questions.
