### ISSUE TITLE
URLField clickable link

### ISSUE THREAD

**Issue by Dleau** [tolomea/django-data-browser#29]
Hi, again. I'm using URLField in models.py.

<img width="380" alt="image" src="https://user-images.githubusercontent.com/3460819/114319974-c2b6a180-9ae1-11eb-8a7d-b142a9d28531.png">

In /admin, the field product_url shows as a clickable link.

<img width="658" alt="image" src="https://user-images.githubusercontent.com/3460819/114319952-a87cc380-9ae1-11eb-9cbe-20425e0e48d2.png">

But in /data-browser, it does not. How could I make this field a clickable link? 

<img width="526" alt="image" src="https://user-images.githubusercontent.com/3460819/114319936-9733b700-9ae1-11eb-97c9-ef4e66afd113.png">

Thank you for the help!! Again, this DDB project is amazing.

**Comment by tolomea** [comment]
That's a bug, I'll get that fixed for you.

**Comment by tolomea** [comment]
That's in the 4.0.1 release I just did, let me know how it works out

**Comment by Dleau** [comment]
Fixed! Thank you so much!

**Comment by tolomea** [comment]
I was thinking about this some more and I've moved the rendering of those links to the frontend (also for image and file fields) this has two notable impacts.

1: they will show as strings in JSON and CSV
2: they will have all the same filtering options as strings

This is in the 4.0.2 release I just did.
