### ISSUE TITLE
Python 3.6 SyntaxError: future feature annotations is not defined

### ISSUE THREAD

**Issue by jayvdb** [tolomea/django-data-browser#3]
setup.py says it is puython 3.6 compatible, however..
```py
/python3.6/site-packages/data_browser/models.py", line 1
    from __future__ import annotations
                                     ^
SyntaxError: future feature annotations is not defined
```

**Comment by tolomea** [comment]
That's my reward for not having CI sorted, I will look into what can be done about removing the future import.

**Comment by jayvdb** [comment]
I'm flexible; IMO targetting 3.7+ is ok.

We disable this app in production anyways, but it is great for dev work, and our devs are usually on 3.8.  Thanks for the great app.

**Comment by tolomea** [comment]
That was surprisingly easy, the 2.0.4 version works with 3.6. And now there's CI and Tox to make sure it doesn't break again and to check that we're good with all of the >2 verions of Django.

**Comment by jayvdb** [comment]
Thanks
