### ISSUE TITLE
Missing static files after updating to django 5.0

### ISSUE THREAD

**Issue by lekjos** [tolomea/django-data-browser#73]
Hey, great package!

I recently updated our repo to Django 5 / python 3.12 from 4.0 python 3.8. After making the upgrade, we're seeing a 404 on several static files:

<img width="812" alt="image" src="https://github.com/tolomea/django-data-browser/assets/29488764/b9d30e8e-4114-4c9d-a5e7-09e46a05464d">
<img width="1161" alt="image" src="https://github.com/tolomea/django-data-browser/assets/29488764/ad9e4ed9-bb3f-4ff6-989c-b8afea017b79">

Anyone else seen anything like this?

**Comment by tolomea** [comment]
Thank you for the bug report.

Am I correct in guessing that this is breaking DDB?

I can confirm it works correctly for me, so it's likely an environment issue.

Is this in development and/or production? aka debug = True / False / Both

What operating systems are you experiencing it on?

It looks a lot like this former issue https://github.com/tolomea/django-data-browser/issues/45 which is about some operating systems (Windows) not declaring the mimetype for .js files by default. If it is that it can be fixed either by adding the mimetype in the registry or in your settings.py.

**Comment by tolomea** [comment]
Also working with Py3.12

**Comment by lekjos** [comment]
Hi @tolomea, 
Correct, this is preventing the DDB frontend from loading.

I've tested it on an M2 Mac running debug mode and on our Azure App Service deployment via Python3.12-slim docker image with DEBUG=False and same result in both cases.

I'll experiment with changing mimetype in the morning--thanks!

**Comment by lekjos** [comment]
Figured out the issue -- it was stupid haha. We were overriding your `index.html` template to add some custom branding and when we updated python/django, we also bumped your package to a newer version that wasn't compatible with our customizations...

Sorry for bugging you and thanks for the quick response confirming that things are working on your end!

**Comment by tolomea** [comment]
No problem, I'm glad you got it figured out.

I try to limit the amount the layout and CSS change especially the page level stuff. The more detailed stuff is harder.

Except for major versions, then all bets are off.
