### ISSUE TITLE
[enhancement] add OneToOneField into query.py

### ISSUE THREAD

**Issue by ghiewa** [tolomea/django-data-browser#9]
@tolomea 
Possible, to include OneToOneField into query.py. then can 'drap / drop' OneToOneField in design view.

**Comment by tolomea** [comment]
I will look into this, I don't recall there being a reason for it not being in there, so probably it's an oversight due to it not being very common.

**Comment by tolomea** [comment]
I've released an update for this, give it a go and let me know if it doesn't cover your needs.
